### ISSUE TITLE
Represent NUMA information from sysfs

### ISSUE THREAD

**Issue by jbainbri** [ryran/xsos#101]
NUMA systems represent their NUMA topology (CPUs, memory, devices local to northbridge) in sysfs.

It would be great if xsos could show this.

CPUS are at: `/sys/devices/system/node/node0/cpulist`

For memory, `meminfo` is in the same directory as above, though it may also be useful to find which offset of memory is where (eg: first 16Gb in Node 0, next 16Gb in Node 1, and so on)

I know network PCIe devices are at: `/sys/class/net/<devname>/device/numa_node` though any PCIe device can be local to a node, as the PCIe bus is on the northbridge.

**Comment by ryran** [comment]
@jbainbri : ping

**Comment by jbainbri** [comment]
I have not remembered to do this very well have I. Leave it with me, I'll have something for you soon.

**Comment by ryran** [comment]
Woo hoo!

**Comment by jbainbri** [comment]
Upon further investigation, we don't collect per-device NUMA info in sos, so I'll take care of that upstream and re-open this issue later.

**Comment by ryran** [comment]
Aww bummer. OK.
