### ISSUE TITLE
Display pause frame counters in ETHTOOL Interface Errors output

### ISSUE THREAD

**Issue by ptalbert** [ryran/xsos#112]
Pause frames indicate congestion on the network segment. Frequent pause frames can cause a severe performance degradation.

$ grep pause sos_commands/networking/ethtool_-S_eth1
     rx_pause_frames: 95331
     rx_constant_pause_events: 0
     tx_pause_frames: 0

I think reporting any instance of the word "pause" as a potential error would be safe. I don't know of any "good" pauses that might be reported.

**Comment by ryran** [comment]
@ptalbert : Done. You can update with `xsos --update` if you want the change NAOW.
