### ISSUE TITLE
Provide PCI address information in ethtool output?

### ISSUE THREAD

**Issue by ptalbert** [ryran/xsos#114]
Having the PCI address in the ethtool output allows one to quickly see which interfaces are part of the same physical hardware.

ethtool -i provides the addressing information.

**Comment by ryran** [comment]
Give me some ideas on how to change the display to include this info.

**Comment by ryran** [comment]
@ptalbert : is this good enough or did you have something else in mind? All suggestions welcome.

![xsos-ethtool-pci](https://cloud.githubusercontent.com/assets/1092618/5786210/5dd1733e-9daf-11e4-96c5-87b54be340e8.png)

**Comment by ryran** [comment]
Merged. In xsos v0.5.9.
