### ISSUE TITLE
xsos -y seems to be executed successfully but exits with 1

### ISSUE THREAD

**Issue by lathan** [ryran/xsos#125]
I execute `xsos -y` (either against a sosreport or localhost). It puts me into `less`. When I exit `less` with `q`, the exit status is 1. Why?

Will look into it a bit more.

**Comment by lathan** [comment]
Maybe this has something to do with stderr redirection?

**Comment by ryran** [comment]
> I execute `xsos -y` (either against a sosreport or localhost). It puts me into `less`. When I exit `less` with `q`, the exit status is 1. Why?

That's a great question. I just spent 10 minutes trying to figure it out and I don't have an answer. I guess I had never noticed. Counter question: does this matter to you?

**Comment by lathan** [comment]
It matters cause I want to know why! :P
But not in any other practical sense.

**Comment by ryran** [comment]
Yeah. Very weird indeed, but I don't care enough to debug it. Sorry!

**Comment by lathan** [comment]
I found it. It's because of the very last line.

```bash
[[ $XSOS_OUTPUT_HANDLER == cat ]] && cat $stderr_file >&2
```

What happens is, when a pager/output-handler like `less` is used, that first part before the `&&` is always false and returns 1, and that's the very last thing that gets executed, so the exit code of `xsos` is 1.

A simple and obvious way to address this would be to keep an `exit 0` as the very last line.

**Comment by ryran** [comment]
Innnnnnnteresting.
