### ISSUE TITLE
expected VLAN tagged interface ethtool filenames not always valid

### ISSUE THREAD

**Issue by ptalbert** [ryran/xsos#134]
I should be better at describing problems.

When producing the ETHTOOL output, xsos seems to assume the sos report networking plugin filename for a given VLAN interface to be something that doesn't exists.

Bond VLAN interface name: bond0.0@bond0

xsos is looking for ethtool_bond0.0:

cat: ethtool_bond0.0: No such file or directory

Actual file name:

ethtool_bond0.0_bond0

Granted, the output is mostly useless, but at least the cat error could be avoided!

$ cat sos_commands/networking/ethtool_bond0.0_bond0 
Cannot get device settings: No such device
Cannot get wake-on-lan settings: No such device
Cannot get message level: No such device
Cannot get link status: No such device
Settings for bond0.0@bond0:
No data available

**Comment by ryran** [comment]
Whoops!  Fixed, merged, and available with `xsos -U` ... will be in next rpm whenever that is.
Thanks Patrick.
