### ISSUE TITLE
Storage values should be in GB and TB not in GiB and TiB

### ISSUE THREAD

**Issue by alexandrujuncu** [ryran/xsos#143]
Hi!

This caught my eye: any particular reason why the storage values are expressed in multiples of 1024 and not of 1000?

Because, indeed, for memory, it's more relevant to use binary prefixes (by the way, you get points for using correct notations). But for storage, multiples of 1000 are more common and intuitive.

Thanks!

**Comment by ryran** [comment]
> This caught my eye: any particular reason why the storage values are expressed in multiples of 1024 and not of 1000?
> Because, indeed, for memory, it's more relevant to use binary prefixes ... But for storage, multiples of 1000 are more common and intuitive.

"more intuitive" is too subjective for me to comment on.
"more common" definitely does not agree with my experience. 
 
All the tools I use in linux print storage values by default with binary prefixes, e.g.:

```
[root@jiop ~]# lvs
  LV   VG     Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  root rootvg -wi-ao---- 100.00g                                                    
  swap rootvg -wi-ao----   8.00g                                                    
[root@jiop ~]# lsblk
NAME            MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda               8:0    0 465.8G  0 disk 
├─sda1            8:1    0   500M  0 part /boot
└─sda2            8:2    0   300G  0 part 
  ├─rootvg-swap 253:0    0     8G  0 lvm  [SWAP]
  └─rootvg-root 253:1    0   100G  0 lvm  /
sr0              11:0    1  1024M  0 rom  
[root@jiop ~]# grep dm-0 /proc/partitions 
 253        0    8388608 dm-0
[root@jiop ~]# k 8388608
B           KiB      MiB      GiB   TiB   PiB  EiB
8589934592  8388608  8192.00  8.00  .007  0    0
[root@jiop ~]# 
[root@jiop ~]# grep sda1 /proc/partitions 
   8        1     512000 sda1
[root@jiop ~]# k 512000
B          KiB     MiB     GiB  TiB  PiB  EiB
524288000  512000  500.00  .48  0    0    0
[root@jiop ~]# dd if=/dev/zero bs=1M count=100 of=tmp.img
100+0 records in
100+0 records out
104857600 bytes (105 MB) copied, 0.0386395 s, 2.7 GB/s
[root@jiop ~]# ll -h tmp.img 
-rw-r--r--. 1 root root 100M May 29 16:18 tmp.img
[root@jiop ~]# ll tmp.img
-rw-r--r--. 1 root root 104857600 May 29 16:18 tmp.img
[root@jiop ~]# b 104857600
B          KiB       MiB     GiB  TiB  PiB  EiB
104857600  102400.0  100.00  .09  0    0    0
[root@jiop ~]# 
```

I almost never encounter SI (decimal) prefixes ... virtually only see them used by storage manufacturers.
