### ISSUE TITLE
Provide complete /proc/net/dev output

### ISSUE THREAD

**Issue by ptalbert** [ryran/xsos#183]
Currently, xsos --netdev does not show RX Frame and TX FIFO counters from /proc/net/dev. Can these be added to the output?

Maybe too complex, but to limit the width of the output perhaps xsos would only print any given error counter column if any of the rows are non-zero?

**Comment by ryran** [comment]
Not too complex..just possibly confusing, but yeah I'll try it out.

**Comment by ryran** [comment]
Done and ready for the next release which is long overdue but I'm debating whether to do this:

![netdev split](http://people.redhat.com/rsawhill/scratch/xsos-netdev-new.png)

Or this:

![netdev wide](http://people.redhat.com/rsawhill/scratch/xsos-netdev-new-wide.png)

**Comment by jbainbri** [comment]
Wow nice! Please do the first one, because the second option is too wide.

**Comment by Aftermath** [comment]
Agreed, with option 1!

**Comment by ryran** [comment]
@jbainbri just blew my mind.

>  like, if the packet was TxDropped, it wasn't Tx'ed, so you'd increment
> the dropped counter and not the Tx counter

Everything is a lie. OMG I've been doing it wrong all along.

**Comment by evdanil** [comment]
option 1
