### ISSUE TITLE
xsos praise

### ISSUE THREAD

**Issue by samelstob** [ryran/xsos#192]
@ryran 

I couldn't get hold of you via twitter or email so I just I am taking this route to praise xsos!

I am finding it immensely helpful in summarising system information at the start of a troubleshooting process.

It's also one of the smartest examples how UX applies to the console as much as the web (in my opinion).

Thanks for creating this and apologies for opening an issue.

Sam
https://twitter.com/samelstob

**Comment by ryran** [comment]
@samelstob 
Thanks so much for taking the time to give feedback Sam! I *really really* appreciate it! Obviously I've put tons of time into making the layout as useful as possible so having someone make note of that makes me so happy. If you ever have any ideas for improvement, don't hesitate to add a new issue.
