### ISSUE TITLE
[rfe] multiple directory support

### ISSUE THREAD

**Issue by strikerttd** [ryran/xsos#193]
RFE request to implement multiple directory support for xsos when specifying the archived OS dir (sosreport).

$ xsos dir1 dir2 dir3

**Comment by ryran** [comment]
Hey there striker. How would you propose displaying that? I guess I don't understand. Can you describe your use-case?

**Comment by superjamie** [comment]
IMO this is not a feature to be solved by xsos.

`find -type d -maxdepth 1 -print -exec xsos {} \;` will probably do what you're after

**Comment by ryran** [comment]
Agreed. There are plenty of ways to loop over multiple directories. I know xsos is all about making things easier, but this is something that would just be too weird to implement.
