### ISSUE TITLE
bios module assumes MB from dmidecode (dmidecode memory total wrong)

### ISSUE THREAD

**Issue by j47996** [ryran/xsos#203]
Description of problem:

  "xsos -a ." against the sosreport of a large system claims it has a total
of 2GB of memory, when there is actually 2GB

Version-Release number of selected component (if applicable):

  Version info: xsos v0.7.8 last mod 2015/02/16

How reproducible:

Steps to Reproduce:
1. sosreport a large system (seen for a Bull 120-core, 2TB)
2. xsos -a .
3.

Actual results:

  DMIDECODE
  BIOS:
    Vend: Bull
    Vers: BIOSX05.021.02.015
    Date: 04/02/2015
    BIOS Rev: 109.21
    FW Rev:  
  System:
    Mfr:  BULL
    Prod: bullion S
    Vers: 2.0
    Ser:  XAN-S18-01765
    UUID: A5C304E4-508E-41C5-A95C-27FB4947DA0E
  CPU:
    8 of 16 CPU sockets populated, 15 cores/30 threads per CPU
    120 total cores, 240 total threads
    Mfr:  Not Specified
    Fam:  <OUT OF SPEC>
    Freq: 2800 MHz
    Vers: Not Specified
  Memory:
    2048 MB (2 GB) total
    64 of 192 DIMMs populated (system max capacity 6 TB)

Expected results:

  Memory:
    2048 GB (2 TB) total

Additional info:

 The "MEMORY" section of the output is more reasonable:

  MEMORY
  Stats graphed as percent of MemTotal:
    MemUsed    ▊▊▊▊▊▊▊▊▊▊▊▊▊▊▊▊▊▊▊▊▊▊▊▊▊▊........................  52.6%
    Buffers    ..................................................   0.0%
    Cached     ▊.................................................   1.0%
    HugePages  ..................................................   0.0%
    Dirty      ..................................................   0.0%
  RAM:
    2019 GiB total ram
    1061.3 GiB (53%) used
    1041.1 GiB (52%) used excluding Buffers/Cached
    0.01 GiB (0%) dirty

**Comment by bmr-cymru** [comment]
The report data (at least the dmidecode file) are likely going to be helpful in debugging this; it is unclear from the information posted whether this is a fault in the underlying data, or xsos' processing (but since it's reporting correct values for MEMORY my first guess is wonky dmidecode - which may be the tool or the firmware at fault).

**Comment by ryran** [comment]
Hi @j47996 
Here's how xsos calculates the total memory from dmidecode:

```
gawk 'BEGIN { RS="\nHandle" } /Physical Memory Array|Memory Device/' <<<"$dmidecode_input" |
    gawk -vH3="${c[H3]}" -vH2="${c[H2]}" -vH0="${c[0]}" -vH_IMP="${c[Imp]}" '
      /Size:/ { NumDimmSlots ++; if ($2 ~ /^[0-9]/) { NumDimms ++; SumRam+=$2 } }
      /Maximum Capacity:/ { MaxRam = $3" "$4 }
      END {
        printf "    %d MB (%.0f GB) total\n", SumRam, SumRam/1024
        printf "    %d of %d DIMMs populated (system max capacity %s)\n",
          NumDimms, NumDimmSlots, MaxRam
      }
    '
```

What it's looking for and expecting is dmidecode input like the following:

```
Handle 0x1100, DMI type 17, 34 bytes
Memory Device
        Array Handle: 0x1000
        Error Information Handle: Not Provided
        Total Width: 72 bits
        Data Width: 64 bits
        Size: 8192 MB
...
```

In all my years, I have never seen `dmidecode` print anything other than `MB` as the suffix in that `Size:` line. Without looking at the code, I just made the lazy-ass assumption early on that *that* was the only possibility.

It sounds like you might be dealing with a system that has that value in GB, so show me the following:

```
cat SOSREPORTDIR/dmidecode | gawk 'BEGIN { RS="\nHandle" } /Physical Memory Array|Memory Device/' | grep Size: | sort | uniq -c
```

**Comment by bmr-cymru** [comment]
> cat SOSREPORTDIR/dmidecode | gawk 'BEGIN { RS="\nHandle" } /Physical Memory Array|Memory Device/' | grep Size: | sort | uniq -c

Here's another gratuitous cat:

```
  /\     /\
  {  `---'  }
  {  O   O  }
  ~~>  V  <~~
   \  \|/  /
    `-----'__
    /     \  `^\_
   {       }\ |\_\_   W
   |  \_/  |/ /  \_\_( )
    \__/  /(_E     \__/
      (  /
       MM
```

;-)

**Comment by bmr-cymru** [comment]
Maybe easier to just dump the whole dmidecode somewhere? in case there are other oddities.

**Comment by ryran** [comment]
LOL @bmr-cymru I'm well aware of how cat was unnecessary in that situation; I chose it for clarity. (There is no such use of cat anywhere in xsos.)

@j47996 please respond back if you want help with this.

**Comment by bmr-cymru** [comment]
SCNR :-)

**Comment by ryran** [comment]
DONE AND DONE.

**Comment by bmr-cymru** [comment]
:+1:
