### ISSUE TITLE
GAWK should be AWK

### ISSUE THREAD

**Issue by wirawan0** [ryran/xsos#204]
Hi, this is a great tool that I came across by accident. I noted one thing: you specifically used "gawk" to run the AWK scripts. This is not always available on every site (for example Debian system did not come with it by default). It is probably better to use "awk" instead of "gawk", assuming you don't use any  GNU-specific extension. Or another way, introduce $AWK environment variable in the script that can be reassigned by user to his/her own AWK implementation.

Wirawan

**Comment by ryran** [comment]
@wirawan0 
Hello Wirawan! A few facts:

* awk scripts make up a huge percentage of xsos
* I've also written some other tools (like Rebooty-inspector) that use a lot of awk
* there have been times when I've used or looked at using GNU-specific awk features
* that said, I honestly I don't remember if there are GNU-specific extensions any of the xsos awk scripts
* I only test with gawk
* at some point I changed all `awk` references in xsos to `gawk` out of safety
* I don't have the bandwidth right now to spend any time on this

So there you go. Unfortunately, all I can recommend is: install gawk.
