### ISSUE TITLE
xsos fails on Mac OS X

### ISSUE THREAD

**Issue by ryran** [ryran/xsos#217]
```
$ xsos somesosreport/
getopt: illegal option -- n
getopt: illegal option -- a
getopt: illegal option -- m
getopt: illegal option -- e
getopt: illegal option -- =
getopt: illegal option -- x
getopt: illegal option -- s
getopt: illegal option -- o
getopt: illegal option -- s
getopt: illegal option -- o
 -- -- 6q:u:v:w:xyzabokcfmdtlerngisp -l scrub,ipv6,rhsupport,wwid:,unit:,threads,verbose:,width:,nocolor,less,more,all,bios,os,kdump,cpu,intrupt,mem,disks,mpath,lspci,ethtool,softirq,netdev,bonding,ip,net,sysctl,ps,B:,C:,F:,M:,D:,T:,L:,R:,N:,G:,I:,P: --
 somesosreport/
Usage: xsos [DISPLAY OPTIONS] [-6abokcfmdtlerngisp] [SOSREPORT ROOT]
  or:  xsos [DISPLAY OPTIONS] {--B|--C|--F|--M|--D|--T|--L|--R|--N|--G|--I|--P FILE}...
  or:  xsos [-?|-h|--help]

Display system info from localhost or extracted sosreport
```

**Comment by ryran** [comment]
Bash has the built-in `getopt` which is crappy and buggy and only supports short options. If you write a program for bash `getopt`, it will be pretty darn cross-platform.

However, I didn't want xsos to be limited to short options (e.g., only `-x` and not `--nocolor`), so I used the much more comprehensive GNU `getopt` program (separate from bash).

For some inscrutable reason, even though Mac OS X would not be possible without many of the included GNU utils (like coreutils or bash itself), Apple decided not to include GNU getopt, so any scripts that rely on it (like xsos) will fail on Mac OS X.

See: https://www.google.com/search?q=gnu+getopt+mac+osx

**Comment by gmeghnag** [comment]
How to make xsos working on MAC:
```
brew install gnu-getopt gawk coreutils
brew link --force gnu-getopt
```
