### ISSUE TITLE
ipaddress plugin no longer functions with sosreport 3.5

### ISSUE THREAD

**Issue by ptalbert** [ryran/xsos#224]
New sosreports no longer collect "ip address", instead they use "ip -d address". xsos understandably then cannot find "ip_address" and bails:

~~~
$ xsos -i .
Warning: './sos_commands/networking/ip_address' file unreadable; skipping ip check
$ ls sos_commands/networking/*address
sos_commands/networking/ip_-d_address
~~~

The sos commit responsible for the change:

https://github.com/sosreport/sos/commit/66289f8edf426845891f40bb9cf8efa951a8391a

The parser in xsos still works fine if you modify it to look for ip_-d_address, but I am not sure about the proper way to have xsos look for either file?

**Comment by ryran** [comment]
@ptalbert Hey Patrick. Thanks for bringing this to my attention!

**Comment by ryran** [comment]
PS: I'll push out a release soon
