### ISSUE TITLE
Suggestion: xsos results output to HTML

### ISSUE THREAD

**Issue by pjhwa** [ryran/xsos#246]
If xsos results might be able to converted to HTML, it would be great using Web browser from web based environment.

**Comment by ryran** [comment]
I agree -- would be awesome! I don't have any plans to do that kind of work.

**Comment by superjamie** [comment]
It would be nice, but it's a rather large job to separate the xsos "processing engine" from the "output engine" to allow variable sorts of output. I don't think any of us have time to work on such a large change unfortunately.

It would be more appropriate to use an existing ANSI-to-HTML tool like those detailed here:
* https://unix.stackexchange.com/questions/44956/converting-colored-output-into-html

Then xsos can focus on making good bash output, and the tool can focus on good conversion from bash ANSI to HTML.
