### ISSUE TITLE
PS CHECK module not working

### ISSUE THREAD

**Issue by ziz0u** [ryran/xsos#282]
```
[root@server ~]# xsos -p
[root@server ~]# xsos --ps
[root@server ~]#
```

Validating with the debug shows the following warning:
**Warning: 'ps/proc/' file unreadable; skipping os check**

**Comment by superjamie** [comment]
Good timing, this is resolved by a recent PR to be merged soon: https://github.com/ryran/xsos/pull/281

**Comment by ziz0u** [comment]
Thank you for your answer
