### ISSUE TITLE
How to install xsos or rsar via yum?

### ISSUE THREAD

**Issue by ryran** [ryran/xsos#67]
Downloading files with `wget` is great and all, but how can we install xsos or rsar with `yum`?

**Comment by 86Luca86** [comment]
Hello Ryan, 
I want to tell you that the "http://people.redhat.com/rsawhill/rpms/latest-rsawaroha-release.rpm" url isn't available anymore, instead we should use the https protocol.

**Comment by superjamie** [comment]
Ryan has not maintained the RPM release for many years. I will remove that from the documentation.
