### ISSUE TITLE
RFE: Add further kdump diagnostics

### ISSUE THREAD

**Issue by tiwillia** [ryran/xsos#81]
Currently, the --kdump option (which is amazing already) does not include a very important factor to determining if a system is configured properly. This is whether or not there is enough space in the place designated for a core to be created. This should be equal to the total amount of memory on the system.

I know the above is a good amount of work, unless you only program it for the default 'path /var/crash' option. 

Additionally, I would like to recommend that the panic sysctls (I.E. kernel.hung_taks_panic = 0) be included in the kdump output. These are helpful for determining if a system will crash on certain events with kdump configured.

**Comment by ryran** [comment]
Never did the thing mentioned in last comment. Closing.
