### ISSUE TITLE
RFE: do something with netstat -s or /proc/net/netstat

### ISSUE THREAD

**Issue by ryran** [ryran/xsos#89]
(Will elaborate.)

**Comment by superjamie** [comment]
The `/proc/net/{dev,netstat,sctp,snmp}` will be better, because we don't include `net-tools` and hence `netstat` in a default EL7 install.

LMK if you need a hand coming up with useful interesting stats, I can make some suggestions.

**Comment by ryran** [comment]
@superjamie Well as you see I originally filed this in January 2014 haha and since I haven't done anything with it in all this time ... it's not going to happen unless one of you networking guys puts together some ideas. :)

**Comment by juanmasg** [comment]
Reviving this :)

I have an initial approach for `/proc/net/netstat`
```
% XSOS_NETSTAT_FILTER_REGEX="fail|drop|kill|delay|reorder|lost|retrans|zero" XSOS_NETSTAT_HIGHLIGHT_REGEX=drop xsos -N .
TCPSackRecoveryFail: 302
TCPDeferAcceptDrop: 1081306
TCPFACKReorder: 9
TCPSlowStartRetrans: 3212
DelayedACKLost: 26016
TCPRenoReorder: 1
DelayedACKs: 35683
TCPLostRetransmit: 7
TCPSACKReorder: 33
TCPLossFailures: 122
SyncookiesFailed: 1343
TCPSackFailures: 14946
TCPWantZeroWindowAdv: 693
TCPTSReorder: 27
TCPToZeroWindowAdv: 210
DelayedACKLocked: 822
ListenDrops: 67714
TCPSynRetrans: 4501
TCPForwardRetrans: 635
TCPFromZeroWindowAdv: 210
TCPFastRetrans: 3581
```

only counters matching `XSOS_NETSTAT_FILTER_REGEX` are printed as long as their value is >0, and counters matching `XSOS_NETSTAT_HIGHLIGHT_REGEX` are highlighted.

@superjamie not sure if you had a different idea in mind??

**Comment by superjamie** [comment]
That's a good idea.

Please add `listen` to the default regex so that we catch SYN floods (https://access.redhat.com/solutions/30453) and full accept backlog (https://access.redhat.com/solutions/3193562).

The TCP Timestamp rejection would be good to include too. Off the top of my head, I *think* that matches with `stamp`.

Do you think it looks better to align the values in a column? Something like `nstat` does, eg:

~~~
TCPSackRecoveryFail:  302
TCPDeferAcceptDrop:   1081306
TCPFACKReorder:       9
...and so on...
~~~

**Comment by juanmasg** [comment]
Yeah I added proper formatting after working on the parsers. The branch is available here https://github.com/juanmasg/xsos/tree/netstat . I't s almost ready.

I also added parsing of `/proc/net/snmp` and `/proc/net/snmp6`.

I'll improve the default regex as suggested and generate the PR later today.

**Comment by juanmasg** [comment]
Added `listen` and `PAWS` keywords to the regex.

It seems that rejects because of timestamp are the `PAWSActive`,`PAWSEstab` and `PAWSPassive` counters:
   ```
   net-tools-2.10% grep PAWS *c            
   statistics.c:    {"PAWSActive", N_("%llu active connections rejected because of time stamp"), opt_number},
   statistics.c:    {"PAWSEstab", N_("%llu packets rejected in established connections because of timestamp"), opt_number},
   statistics.c:    {"PAWSPassive", N_("%llu passive connections rejected because of time stamp"), opt_number},
   ```

PR here https://github.com/ryran/xsos/pull/258

**Comment by superjamie** [comment]
Merged. Thank you very much again!
